SAMPLES: "samples.tsv"
PAIRED: TRUE 
GENOME: "/rds/project/rds-O11U8YqSuCk/SM/annotations/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome"
CONF: "/rds/project/rds-O11U8YqSuCk/SM/annotations/FastQ_Screen_Genomes/fastq_screen.conf" 
MIN_BASE_QUALITY: 5
MEMORY: "-Xmx40g" 
